App/urls.py
from django.urls import path
from .views import *

app_name = '[ZOL]'
urlpatterns = [
    # 首页
    path('',index,name='index'),                                                # 首页
    path('getbanners/',get_banners,name='getbanners'),                          # 大轮播图
    path('getluns/',get_luns,name='getluns'),                                   # 小轮播图
    path('gettuans/',get_tuans,name='gettuans'),                                # 团购
    path('getfloorgoods/',get_floor_goods,name='getfloorgoods'),                # 获取楼层商品

    path('register/',register,name='register'),                                 # 注册
    path('login/',login,name='login'),                                          # 登录
    path('verifycode/', generate_verifycode, name='verifycode'),                # 验证码
    path('logout/', logout, name='logout'),                                     # 注销
    path('addfloorgoods/',add_floor_goods,name='addfloorgoods'),                # 添加楼层商品
    path('addfloor/',add_floor,name='addfloor'),                                # 添加楼层
    path('addclass/', add_class, name='addclass'),                              # 添加分类

    path('goodlist/',good_list,name='goodlist'),                                # 商品列表
    # 商品搜索筛选
    path('goodsearch/<brand_name>/<min_price>/<max_price>/<feature>/<network>/<int:sort_by>/<key_word>/',
         good_search,name='goodsearch'),
    path('add_brand/',add_brand,name='addbrand'),                               # 添加品牌
    path('gooddetail/<id>/',good_detail,name='gooddetail'),                     # 商品详情

    # 购物车
    path('addcart/',add_goods_to_cart,name='addcart'),                          # 添加商品至购物车
    path('cart/',cart,name='cart'),                                             # 购物车
    path('numadd/',num_add,name='numadd'),                                      # 商品数量增加
    path('numreduce/',num_reduce,name='numreduce'),                             # 商品数量增加
    path('gooddel/',good_del,name='gooddel'),                                   # 商品删除
    path('selectchange/',select_change,name='selectchange')    ,                # 更改商品勾选状态
    path('allselect/',all_select,name='all_select'),                            # 全选状态判断

    # 购买
    path('buynow/',buy_now,name='buynow'),                                      # 立即购买

    # 订单
    path('postorder/<order_id>/',post_order,name='postorder'),                  # 提交订单
    path('addorder/',add_order,name='addorder'),                                # 增添订单
    path('receiveinfo/',add_receive_info,name='receiveinfo'),                   # 新增收货地址
    path('orderaddreceive/',order_add_receive,name='orderaddreceive'),          # 为订单添加收货信息
    path('order/',order,name='order'),                                          # 订单集合页面
    path('littleskip/<order_id>/<int:status>/',little_skip,name='littleskip'),  # 一个小跳转


    # 支付宝
    path('api/',api,name='api'),                                                # 支付宝接口
    path('pay/', pay,name='pay'),                                               # 支付宝支付
    path('notify/', notify,name='notify'),
    path('result/', result,name='result'),                                      # 支付宝结果
]

ZOL/urls.py
from django.contrib import admin
from django.urls import path,include
from App.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ZOL/',include('App.urls',namespace='ZOL')),
    path('/',index),
]

App/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=32,unique=True)          # 用户名
    phone = models.CharField(max_length=11,unique=True)             # 手机号
    password = models.CharField(max_length=32)                      # 密码
    money = models.FloatField(max_length=32,default=0.00)           # 充钱


# 大轮播图
class Banner(models.Model):
    img = models.CharField(max_length=255)


# 小轮播图
class Lun(models.Model):
    img = models.CharField(max_length=255)


# 团购
class Tuan(models.Model):
    img = models.CharField(max_length=255)


# 首页楼层
class Floor(models.Model):
    img = models.CharField(max_length=255)                         # miansell 左侧大图
    img2 = models.CharField(max_length=255)                        # mianlist 上面大图


# 首页展现的商品
class FloorGood(models.Model):
    product_id = models.IntegerField()                            # 编号  对应json的id
    a = models.CharField(max_length=128)                          # 名称  对应json的a
    p = models.CharField(max_length=255)                          # 描述  对应json的p
    price = models.IntegerField(default=0)                        # 价格
    img = models.CharField(max_length=255)                        # 图片
    floor = models.ForeignKey(Floor,on_delete=models.CASCADE,default=1)


# 祖类
class AncestralType(models.Model):
    name = models.CharField(max_length=32)

# 爷类
class GrandType(models.Model):
    name = models.CharField(max_length=32)
    ancestral = models.ForeignKey(AncestralType, on_delete=models.CASCADE)

# 父类
class ParentType(models.Model):
    name = models.CharField(max_length=32)
    grand = models.ForeignKey(GrandType, on_delete=models.CASCADE)

# 兄类
class BrotherType(models.Model):
    name = models.CharField(max_length=32)
    parent = models.ForeignKey(ParentType, on_delete=models.CASCADE)


# 品牌
class Brand(models.Model):
    cname = models.CharField(max_length=32,unique=True)             # 中文名称
    ename = models.CharField(max_length=32,unique=True)             # 英文名称
    img = models.ImageField(max_length=255,upload_to='./static/img/brands', default='/static/img/default.jpg')      # logo图片

    def __str__(self):
        return self.cname


# 商品(现专指手机)
class Good(models.Model):
    name = models.CharField(max_length=32)                          # 名字
    price = models.FloatField(default=1)                            # 价格
    feature = models.CharField(max_length=255)                      # 特性 (多对多)
    network = models.CharField(max_length=32,default='全网通')      # 网络类型
    color = models.CharField(max_length=32,default='黑色')          # 颜色
    ram = models.CharField(max_length=32,default='8')               # 运行内存
    rom = models.CharField(max_length=32,default='128')             # 只读内存
    img = models.ImageField(max_length=255,upload_to='./static/img/goods',default='/static/img/default.jpg')   # 图片 upload_to 添加相对路径
    desc = models.CharField(max_length=512,default='')              #把前面的所有属性包括的总描述

    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)       # 品牌 (手机：品牌 = n:1)
    type = models.ForeignKey(BrotherType,on_delete=models.CASCADE)  # 兄类

    def __str__(self):
        return self.brand.cname + ' ' + self.name


# 购物车
class Cart(models.Model):
    good = models.ForeignKey(Good,on_delete=models.CASCADE)         # 商品
    user = models.ForeignKey(User,on_delete=models.CASCADE)         # 用户
    num = models.IntegerField(default=1)                            # 商品数量
    color = models.CharField(max_length=32,default='黑色')          # 商品颜色
    ram = models.IntegerField(default=8)                            # 商品运行内存
    rom = models.IntegerField(default=128)                          # 商品只读内存
    is_select = models.BooleanField(default=True)                   # 勾选状态


# 收货信息
class Receive(models.Model):
    person = models.CharField(max_length=32)                        # 收货人
    phone = models.CharField(max_length=11)                         # 收货电话
    address = models.CharField(max_length=255)                      # 收货地址
    user = models.ForeignKey(User,on_delete=models.CASCADE)         # 所属用户


# 订单
class Order(models.Model):
    order_id = models.CharField(max_length=255,unique=True)         # 订单编号
    order_create = models.DateTimeField(auto_now_add=True)          # 订单的创建时间
    order_price = models.FloatField(default=0)                      # 订单价格
    # 订单状态： 0表示未支付， 1表示已支付，2表示待评价，3已退款，4订单已取消,...
    order_status = models.IntegerField(default=0)                   # 订单状态
    user = models.ForeignKey(User,on_delete=models.CASCADE)         # 订单所属的用户
    receive = models.ForeignKey(Receive,on_delete=models.CASCADE,null=True)  # 收货信息


# 订单商品表
class OrderGoods(models.Model):
    goods = models.ForeignKey(Good,on_delete=models.CASCADE)        # 商品
    order = models.ForeignKey(Order,on_delete=models.CASCADE)       # 所属订单
    num = models.IntegerField()                                     # 商品数量
    color = models.CharField(max_length=32, default='黑色')         # 商品颜色
    ram = models.IntegerField(default=8)                            # 商品运行内存
    rom = models.IntegerField(default=128)                          # 商品只读内存

templates/addreceiveinfo.html
{% extends 'base_main.html' %}
{% load static %}

{% block extcss %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/static/css/receive_info.css">
{% endblock %}

{% block extjs %}
    <script src="{% static 'js/receive_info.js' %}"></script>
{% endblock %}

{% block title %}收货地址{% endblock %}


{#注册内容#}
{% block content %}
    <div id="con-receive">
        <div class="sign">
            <h6>收货信息管理</h6>
            <form action="{% url 'ZOL:receiveinfo' %}" method="post">
                {% csrf_token %}
                <span>收货人</span>
                <br>
                <input id="person" type="text" placeholder="  请输入收货人" name="person">
                <br>
                <span>收货手机号</span>
                <br>
                <input id="phone" type="text" placeholder="  请输入收货手机号" name="phone">
                <span id="phone_msg"></span><br>
                <span>收货地址</span>
                <br>
                <input id="address" type="text" placeholder="  请输入收货地址" name="address">
                <br>
                <input id="receive_submit" type="submit" value="保存">
            </form>
        </div>
    </div>
{% endblock %}

templates/alipay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Alipay</title>
</head>
<body>
    <h2>支付宝</h2>

    <button id="pay">支付</button>

    {% load static %}
    <script src="{% static 'js/jquery-3.1.0.js' %}"></script>
    <script src="{% static 'js/alipay.js' %}"></script>
    <script>
        $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
        })
    </script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}

    <title> {% block title %}ZOL{% endblock %} </title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/hover.css' %}">
    {% block extcss %}
    {% endblock %}



</head>
<body>
{#    左侧小红猫#}
    {% block redcat %}

    {% endblock %}
    {#右侧黑条导航#}
    {% block toolbar %}

    {% endblock %}

    {#最上面的导航栏#}
    {% block sign %}

    {% endblock %}

    {#ZOL商城以下#}
    {% block header %}

    {% endblock %}

    {#导航#}
    {% block nav %}

    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
    

    
    <script src="{% static 'js/jquery-3.1.0.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block extjs %}
    {% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'css/display.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'js/base_main.js' %}"></script>
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken:'{{ csrf_token }}'}
        })
    </script>
{% endblock %}

{#最上面的导航栏#}
{% block sign %}
    <div id="sign">
        <div class="toper">
            <div class="login_info">
                <span class="back-home"><a href="{% url 'ZOL:index' %}">商城首页</a> </span>
                {% if user.username %}
                    <span class="nav_user">Hi,{{ user.username }}</span>&nbsp;&nbsp;
                    <span><a href="{% url 'ZOL:logout' %}">注销</a> </span>
                {% else %}
                    <span class="register">Hi~欢迎来到ZOL商城，<a href="{% url 'ZOL:login' %}">请登录</a> </span>&nbsp;&nbsp;&nbsp;
                    <span class="register"><a href="{% url 'ZOL:register' %}">免费注册</a> </span>
                {% endif %}

            </div>
            <ul class="qucik_menu">
                <li class="myorder"><a href="{% url 'ZOL:order' %}">我的订单</a></li>
                <li class="buycenter">
                    <a href="#">买家中心</a>
                    <div class="buycenter_info">
                            <a href="#">我的优惠卷</a><em>0</em>
                            <a href="#">关注的店铺</a><em>0</em>
                            <a href="#">关注的商品</a><em>0</em>
                    </div>
                </li>
                <li class="shopcar"><a href="{% url 'ZOL:cart' %}">购物车</a></li>
                <li class="helpcenter"><a href="#">帮助中心</a></li>
                <li class="separator"><a href="#">|</a></li>
                <li class="menu_phone">
                    <a href="#">手机商城</a>
                    <div class="menu_phone_pic">
                        <img src="/static/img/shop_wechat.png" alt="">
                    </div>
                </li>
                <li class="zolonline"><a href="#">中关村在线</a></li>
                <li class="seller"><a href="#">商家入驻</a></li>
                <li class="con_ser">
                    <a href="#">联系客服</a>
                    <div class="con_ser_phone">
                        400-678-0068
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}


{#ZOL商城头部#}
{% block header %}
    <div id="search">
        <div class="header">
            <div class="logo">
                    <h1>
                        <a href="{% url 'ZOL:index' %}"><img src="/static/img/logo_180x50.png" alt=""></a>
                    </h1>
                    <p>中关村在线旗下网上商城</p>
            </div>

            {#搜索栏,首页，商品列表，商品详情均有此项#}
            {% block search %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/goodslist.html
{% extends 'base_ext.html' %}
{% load static %}

{% block extcss %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/goods.css' %}">
    <link rel="stylesheet" href="{% static 'css/goodslist.css' %}">
{% endblock %}

{% block extjs %}
    {{ block.super }}
    <script src="{% static 'js/goodslist.js' %}"></script>

{#    <script src="{% static 'js/list.js' %}"></script>#}
{% endblock %}

{% block title %}商品列表{% endblock %}

{% block nav_content %}
    <div class="good-list-data">
        <div class="brand">
            <dl>
                <dt>品牌：</dt>
                <dd>
                    <ul class="listlogo">
                        {% for brand in brands %}
                            <li><a href="{% url 'ZOL:goodsearch' brand.cname min_price max_price feature network sort_by key_word %}"><img src="{{ brand.img }}"></a> </li>
                        {% endfor %}

                    </ul>
                </dd>
            </dl>
        </div>
        <div class="price">
            <dl>
                <dt>价格：</dt>
                <dd>
                    <ul class="price-total">
                        <li><a href="{% url 'ZOL:goodsearch' brand_name '0' '500' feature network sort_by key_word %}">500元以下</a> </li>
                        <li><a href="{% url 'ZOL:goodsearch' brand_name '500' '1000' feature network sort_by key_word %}">500-1000元</a> </li>
                        <li><a href="{% url 'ZOL:goodsearch' brand_name '1000' '2000' feature network sort_by key_word %}">1000-200元</a> </li>
                        <li><a href="{% url 'ZOL:goodsearch' brand_name '2000' '3000' feature network sort_by key_word %}">2000-3000元</a> </li>
                        <li><a href="{% url 'ZOL:goodsearch' brand_name '3000' '4000' feature network sort_by key_word %}">3000-4000元</a> </li>
                        <li><a href="{% url 'ZOL:goodsearch' brand_name '4000' '0' feature network sort_by key_word %}">4000元以上</a> </li>

                    </ul>
                </dd>
            </dl>
        </div>
        <div class="character">
            <dl>
                <dt>特性：</dt>
                <dd>
                    <ul class="char-total">
                        {% for feature in features %}
                             <li><a href="{% url 'ZOL:goodsearch' brand_name min_price max_price feature network sort_by key_word %}">{{ feature }}</a> </li>
                        {% endfor %}
                    </ul>
                </dd>
            </dl>
        </div>
        <div class="net-type">
            <dl>
                <dt>网络类型：</dt>
                <dd>
                    <ul class="net-type-total">
                        {% for network in networks %}
                            <li><a href="{% url 'ZOL:goodsearch' brand_name min_price max_price feature network sort_by key_word %}">{{ network }}</a></li>
                        {% endfor %}
                    </ul>
                </dd>
            </dl>
        </div>
    </div>
{#    自加的，用于显示筛选的标签#}
    <div class="goods-list-nav">
{#        <ul class="tags_list">#}
        <ul class="goods-list-titlebar" style="background: #f7f7f7">
            {% if brand_name != '0' %}                                      {# 品牌 #}
                <li class="tags_list">
                    <b style="font-size: 14px;">{{  brand_name }}</b>
                    <a href="{% url 'ZOL:goodsearch' '0' min_price max_price feature network sort_by key_word %}"><span class="glyphicon glyphicon-remove"></span></a>
                </li>
            {% endif %}

            {% if min_price == '0' and max_price == '0' %}          {# 价格 #}
            {% else %}
                {% if max_price == '0' %}
                    <li class="tags_list">
                        <b style="font-size: 14px;">{{ min_price }}元以上</b>
                        <a href="{% url 'ZOL:goodsearch' brand_name '0' '0' feature network sort_by key_word %}"><span class="glyphicon glyphicon-remove"></span></a>
                    </li>
                {% elif min_price == '0' %}
                    <li class="tags_list">
                        <b style="font-size: 14px;">{{ max_price }}元以下</b>
                        <a href="{% url 'ZOL:goodsearch' brand_name '0' '0' feature network sort_by key_word %}"><span class="glyphicon glyphicon-remove"></span></a>
                    </li>
                {% else %}
                    <li class="tags_list">
                        <b style="font-size: 14px;">{{ min_price }} - {{ max_price }}元</b>
                        <a href="{% url 'ZOL:goodsearch' brand_name '0' '0' feature network sort_by key_word %}"><span class="glyphicon glyphicon-remove"></span></a>
                    </li>
                {% endif %}
            {% endif %}

            {% if feature != '0' %}                                 {# 特性 #}
                <li class="tags_list">
                    <b style="font-size: 14px;">{{  feature }}</b>
                    <a href="{% url 'ZOL:goodsearch' brand_name min_price max_price '0' network sort_by key_word %}"><span class="glyphicon glyphicon-remove"></span></a>
                </li>
            {% endif %}
            {% if network != '0' %}                                 {# 网络 #}
                <li class="tags_list">
                    <b style="font-size: 14px;">{{  network }}</b>
                    <a href="{% url 'ZOL:goodsearch' brand_name min_price max_price feature '0' sort_by key_word %}"><span class="glyphicon glyphicon-remove"></span></a>
                </li>
            {% endif %}

        </ul>
    </div>
    <div class=" goods-list-service">
        <span>ZOL商城服务保障</span>
        <ul>
            <li><a href="#"><i><img src="/static/img/sort/xin.png" alt=""></i>行货保证</a></li>
            <li><a href="#"><i><img src="/static/img/sort/piao.png" alt=""></i>发票保障</a></li>
            <li><a href="#"><i><img src="/static/img/sort/sf.png" alt=""></i>顺丰包邮</a></li>
            <li><a href="#"><i><img src="/static/img/sort/tuihuan.png" alt=""></i>无忧退换</a></li>
            <li><a href="#"><i><img src="/static/img/sort/pei.png" alt=""></i>先行赔付</a></li>
        </ul>
    </div>
    <div class="goods-list-nav">
        <ul class="goods-list-titlebar">
            {% for sort in sort_list %}
                {% if forloop.counter0 == sort_by %}
                    <li style="background: #4b4b4b;"><a style="color: white" href="{% url 'ZOL:goodsearch' brand_name min_price max_price feature network forloop.counter0 key_word %}">{{ sort }}</a></li>
                {% else %}
                    <li><a href="{% url 'ZOL:goodsearch' brand_name min_price max_price feature network forloop.counter0 key_word %}">{{ sort }}</a></li>
                {% endif %}


            {% endfor %}
        </ul>
        <ul class="goods-list-detail">
            {% for good in goods %}
                <li>
                    <div>
                        <a href="{% url 'ZOL:gooddetail' good.id %}">
                            <img src="{{ good.img }}">
                            <div class="goods-title">
                                {{ good.brand.cname }}&nbsp;{{ good.brand.ename.title }}&nbsp;
                                {{ good.name }}【{{ good.feature }}】
                            </div>
                            <span>￥{{ good.price }}</span>
                        </a>
                    </div>
                </li>
            {% endfor %}

        </ul>
    </div>
{% endblock %}

templates/login.html
{% extends 'base_main.html' %}
{% load static %}

{% block extcss %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/static/css/register.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
{% endblock %}

{% block extjs %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

{% block title %}登录{% endblock %}

{#把顶部导航栏去掉#}
{% block sign %}
{% endblock %}

{#登录内容#}
{% block content %}
    <div id="login">
        <div class="login">
            <div class="nav">
                <img src="/static/img/login.jpg">
            </div>
            <div class="sign">
                <h6>登录ZOL商城<span class="phonelogin"><a href="#">手机动态密码登录</a>
                </span></h6>
                <form action="{% url 'ZOL:login' %}" method="post">
                    {% csrf_token %}
                    <input id="user" type="text" placeholder="  手机号/用户名" name="name">
                    <br>{{ errors.name }}
                    <input id="pwd" type="password" placeholder="  密码" name="password">
                    <br>{{ errors.password }}
                    <input class="sure" type="text" placeholder="  输入验证码" name="vcode">
    {#                暂未用ajax进行验证码重载#}
                    <img src="/ZOL/verifycode/" class="vcode">
                    <br><p style="color: red">{{ msg }}</p>
                    <a href="{% url 'ZOL:register' %}"><span class="forget" style="float: left">还未注册?</span></a>
                    <span class="forget">忘记密码?</span>
                    <br><br>
                    <input id="enter" type="submit" value="登  录">
                </form>
                <div class="linkparter">
                    <ul>
                        <li>合作账号登录:</li>
                        <li style="cursor: pointer;"><img src="/static/img/login/weibo.png" alt=""></li>
                        <li style="cursor: pointer;"><img src="/static/img/login/QQ.png" alt=""> </li>
                        <li style="cursor: pointer;"><img src="/static/img/login/zhifu.png" alt=""> </li>
                        <li style="cursor: pointer;"><img src="/static/img/login/baidu.png" alt=""> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/order.html
{% extends 'base_main.html' %}
{% load static %}

{% block extcss %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/static/css/statement.css">
    <link rel="stylesheet" type="text/css" href="/static/css/order.css">
{% endblock %}

{% block extjs %}
    {{ block.super }}
    <script>document.write('<script src="//' + (location.host || 'localhost').split(':')[0] + ':35929/livereload.js?snipver=1"></' + 'script>')</script>
    <script src="{% static 'js/statement.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    <script src="{% static 'js/order.js' %}"></script>
{% endblock %}

{% block title %}购物车{% endblock %}

{#把头部去掉#}
{% block header %}
{% endblock %}

{% block content %}
    <div id="content">
        <br>
        <div class="title"><span>全部订单</span></div>
        <div class="goodtotal">
            <table>
                <tbody>
                <tr>
                    <th class="cell1">订单编号</th>
                    <th class="cell2">时间</th>
                    <th class="cell3">信息</th>
                    <th class="cell4">金额</th>
                    <th class="cell5">收货地址</th>
                    <th class="cell2">操作</th>
                </tr>
                {% for order in orders %}
                    <tr class="order_list">
                        <td>{{ order.order_id }}</td>
                        <td>{{ order.order_create }}</td>
                        <td>
                            {% for goods in order.ordergoods_set.all %}
                                <p>{{ goods.goods.brand.cname }} {{ goods.goods.name }} * {{ goods.num }}</p>
                            {% endfor %}
                        </td>
                        <td>{{ order.order_price }}</td>
                        <td>
                            {% if order.receive %}
                                <p></p>收货人：<span>{{ order.receive.person }}</span></p>
                                <p>收货电话：<span>{{ order.receive.phone }}</span></p>
                                <p>收货地址：<span>{{ order.receive.address }}</span></p>
                            {% else %}
                                <a class="toreceive" href="{% url 'ZOL:littleskip' order.order_id 1 %}">添加收货地址</a>
                            {% endif %}
                        </td>
                        <td>
                            {% if order.order_status == 1 %}
                                <p>已支付</p>
                            {% else %}
                                <p><a class="topay" href="{% url 'ZOL:littleskip' order.order_id 2 %}">去支付</a></p>
                            {% endif %}

                        </td>
                    </tr>
                {% endfor %}


{#                {% for cart in carts %}#}
{#                    <tr class="good_list" cartid="{{ cart.id }}">#}
{#                        <td class="good_img">#}
{#                            <span class="good_select"></span>#}
{#                            <img src="{{ cart.good.img }}" >#}
{#                            <span>{{ cart.good.brand.cname }} {{ cart.good.name }}</span>#}
{#                        </td>#}
{#                        <td class="good_version">#}
{#                            <span>#}
{#                                颜色：{{ cart.color }}<br>#}
{#                                运行内存：{{ cart.ram }}<br>#}
{#                                只读内存：{{ cart.rom }}#}
{#                            </span>#}
{#                        </td>#}
{#                        <td class="good_price">#}
{#                            ¥&nbsp;<span>{{ cart.good.price }}</span>#}
{#                        </td>#}
{#                        <td class="good_num">#}
{#                            <button class="reduce">-</button>&nbsp;#}
{#                            <span>{{ cart.num }}</span>&nbsp;#}
{#                            <button class="add">+</button>#}
{#                        </td>#}
{#                        <td class="good_total">#}
{#                            ¥<span></span>#}
{#                        </td>#}
{#                        <td class="good_del">#}
{#                            <a href="#" class="del">删除</a>#}
{#                        </td>#}
{#                    </tr>#}
{#                {% endfor %}#}

            </tbody></table>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base_main.html' %}
{% load static %}

{% block extcss %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    <link rel="stylesheet" type="text/css" href="/static/css/register.css">

{% endblock %}

{% block extjs %}
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block title %}注册{% endblock %}

{#把顶部导航栏去掉#}
{% block sign %}
{% endblock %}

{#注册内容#}
{% block content %}
    <div id="con-register">
        <div class="sign">
            <h6>注册ZOL商城</h6>
            <form action="{% url 'ZOL:register' %}" method="post">
                {% csrf_token %}
                <span>用户名</span>
                <br>
                <input id="username" type="text" placeholder="  请输入用户名(2到16位)" name="username"><i>{{ errors.username }}</i>
                <br>
                <span>手机号</span>
                <br>
                <input id="phone" type="text" placeholder="  请输入手机号" name="phone"><i>{{ errors.phone }}</i>
                <br>
                <span>密码</span>
                <br>
                <input id="pwd" type="password" placeholder="  密码(6到18位)" name="password">
                <i>{{ errors.password }}</i>
                <br>
                <span>确认密码</span>
                <br>
                <input id="pwdc" type="password" placeholder="  请再次输入密码" name="password2">
                <i>{{ errors.password2 }}</i>
                <br>
                <span>验证码</span>
                <br>
                <input class="sure" type="text" placeholder="  输入验证码" name="vcode">
{#                暂未用ajax进行验证码重载#}
{#                <a href="{% url 'ZOL:register' %}"><img src="{% url 'ZOL:verifycode' %}" class="code"></a>#}
                <img src="/ZOL/verifycode/" class="vcode">
                <br><p style="color: red">{{ msg }}</p>
                <input id="register" type="submit" value="注册">
            </form>
            <div class="linkparter">
                <ul>
                    <li>合作账号登录:</li>
                    <li><img src="/static/img/login/weibo.png" alt=""></li>
                    <li><img src="/static/img/login/QQ.png" alt=""> </li>
                    <li><img src="/static/img/login/zhifu.png" alt=""> </li>
                    <li><img src="/static/img/login/baidu.png" alt=""> </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}